# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Send POST request with json body
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=jerry&password=1qaz2wsx

###

GET http://localhost:8080/test?h=asasdf&a=1231
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZXJyeTEiLCJleHAiOjE1NjMxMTA1MzMsImlhdCI6MTU2MzEwNjkzM30.RhDXVlfYx7NpoZAkVkrQoJehNiR3eZSwJs0D_bAhBVE

###

GET http://localhost:8080/test/test4
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZXJyeTEiLCJleHAiOjE1NjMxMTA1MzMsImlhdCI6MTU2MzEwNjkzM30.RhDXVlfYx7NpoZAkVkrQoJehNiR3eZSwJs0D_bAhBVE

###

GET http://localhost:8080/test/menu1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZXJyeTEiLCJleHAiOjE1NjMxMTA1MzMsImlhdCI6MTU2MzEwNjkzM30.RhDXVlfYx7NpoZAkVkrQoJehNiR3eZSwJs0D_bAhBVE

###
