-- auto Generated on 2019-08-27
-- DROP TABLE IF EXISTS t_privilege;
CREATE TABLE t_privilege(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'createTime',
	modifyTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'modifyTime',
	`name` VARCHAR (50) NOT NULL COMMENT 'name',
	`path` VARCHAR (255) NOT NULL COMMENT 'path',
	remark VARCHAR (50) NOT NULL COMMENT 'remark',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_privilege';
