-- auto Generated on 2019-08-24
-- DROP TABLE IF EXISTS t_role;
CREATE TABLE t_role(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'createTime',
	modifyTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'modifyTime',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'remark',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_role';
