-- auto Generated on 2019-08-24
DROP TABLE IF EXISTS t_user;
CREATE TABLE t_user(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'createTime',
	modifyTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'modifyTime',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'remark',
	username VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'username',
	`password` VARCHAR (255) NOT NULL DEFAULT '' COMMENT 'password',
	tokenSalt VARCHAR (255) NOT NULL DEFAULT '' COMMENT 'tokenSalt',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_user';
